# Generated by Django 5.2.11 on 2026-02-25 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_items', models.PositiveIntegerField(default=6)),
                ('max_items', models.PositiveIntegerField(default=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BundleTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_quantity', models.PositiveIntegerField(default=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('bundle_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bundles.bundletemplate')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundle_items', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('bundle_template', 'product')},
            },
        ),
    ]
