# Generated by Django 5.2.11 on 2026-02-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundletemplate',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bundletemplate',
            name='description_he',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bundletemplate',
            name='name_en',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='bundletemplate',
            name='name_he',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='bundletemplate',
            name='name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='bundletemplate',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
    ]
