# Generated by Django 5.2.11 on 2026-09-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_description_en_category_description_he_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('bagel', 'Bagel'), ('extra', 'Extra')], default='bagel', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='specialty_upcharge_cents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
