# Generated by Django 5.2.11 on 2026-09-06 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_product_product_type_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagelPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(unique=True)),
                ('price_cents', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['quantity'],
            },
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('pickup_starts_at', models.DateTimeField()),
                ('pickup_ends_at', models.DateTimeField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('bagel_capacity', models.PositiveIntegerField(default=72)),
                ('max_bagels_per_order', models.PositiveIntegerField(default=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['opens_at'],
            },
        ),
        migrations.CreateModel(
            name='DropProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('price_override_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_entries', to='drops.drop')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drop_entries', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='drop',
            name='products',
            field=models.ManyToManyField(related_name='drops', through='drops.DropProduct', to='catalog.product'),
        ),
        migrations.CreateModel(
            name='DropReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bagel_quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('held', 'Held for payment'), ('confirmed', 'Confirmed'), ('released', 'Released')], default='held', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='drops.drop')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_reservation', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dropproduct',
            constraint=models.UniqueConstraint(fields=('drop', 'product'), name='unique_drop_product'),
        ),
    ]
