# Generated by Django 5.2.11 on 2026-09-06 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0002_seed_bagel_price_tiers'),
        ('notifications', '0002_cateringinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_capacity', 'Low capacity'), ('sold_out', 'Sold out')], max_length=30)),
                ('remaining_bagels', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='drops.drop')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('drop', 'alert_type'), name='unique_drop_alert_type')],
            },
        ),
    ]
