# Generated by Django 5.2.11 on 2026-09-06 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0002_seed_bagel_price_tiers'),
        ('notifications', '0003_dropalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('drop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='announcement', to='drops.drop')),
            ],
        ),
    ]
