# Generated by Django 5.2.11 on 2026-09-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_dropannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('topic', models.CharField(choices=[('order', 'Existing order'), ('pickup', 'Pickup question'), ('product', 'Product or ingredients'), ('feedback', 'Feedback'), ('other', 'Something else')], default='other', max_length=30)),
                ('order_number', models.CharField(blank=True, max_length=24)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
