# Generated by Django 5.2.11 on 2026-09-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('home', 'Home page'), ('menu', 'Menu page'), ('about', 'About page'), ('contact', 'Contact page'), ('catering', 'Catering page'), ('blog', 'Blog page')], max_length=30, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'page metadata',
                'verbose_name_plural': 'page metadata',
                'ordering': ['id'],
            },
        ),
    ]
