# Generated by Django 5.2.11 on 2026-09-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_bagel_quantity_order_discount_cents_order_drop'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
